### ISSUE TITLE
弹出时和其他动画抛异常

### ISSUE THREAD

**Issue by Joslyn-Chen** [razerdp/BasePopup#138]
- 系统版本：8.0.0
 - 库版本：2.1.7
 - 问题描述/重现步骤：当执行添加购物车[动画](https://github.com/paradoxie/ShopAnimDemo)（一个抛物线）后，再点击弹出就没反应了。
 - 问题代码/截图：mShoppingCarPopup.showPopupWindow();
 - 报错信息：
`android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7ffffffe
    at android.content.res.ResourcesImpl.getResourceEntryName(ResourcesImpl.java:271)
    at android.content.res.Resources.getResourceEntryName(Resources.java:2006)
    at razerdp.util.PopupUiUtils.checkHasNavigationBar(PopupUiUtils.java:71)
    at razerdp.util.PopupUiUtils.getNavigationBarHeight(PopupUiUtils.java:36)
    at razerdp.util.PopupUiUtils.getScreenHeightCompat(PopupUiUtils.java:94)
    at razerdp.basepopup.BasePopupWindow.getScreenHeight(BasePopupWindow.java:2038)
    at razerdp.basepopup.BasePopupWindow.onCalculateOffsetAdjust(BasePopupWindow.java:1059)
    at razerdp.basepopup.BasePopupWindow.calculateOffset(BasePopupWindow.java:974)
    at razerdp.basepopup.BasePopupWindow.tryToShowPopup(BasePopupWindow.java:818)
    at razerdp.basepopup.BasePopupWindow.showPopupWindow(BasePopupWindow.java:699)
    at com.jfb.jht.popup.ShopShoppingCarPopup.showPopupWindow(ShopShoppingCarPopup.java:60)
    at com.jfb.jht.activity.ShopActivity.showShoppingCar(ShopActivity.java:286)
    at com.jfb.jht.activity.ShopActivity.onViewClicked(ShopActivity.java:345)
    at com.jfb.jht.activity.ShopActivity_ViewBinding$6.doClick(ShopActivity_ViewBinding.java:119)
    at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
    at android.view.View.performClick(View.java:6266)
    at android.view.View$PerformClick.run(View.java:24730)
    at android.os.Handler.handleCallback(Handler.java:793)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:173)
    at android.app.ActivityThread.main(ActivityThread.java:6698)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)`

---

**Comment by razerdp** [comment]
oh....估计是某个id找不到resourceentry，，不过这理论上不应该的- -你是不是decorView添加过什么？

**Comment by razerdp** [comment]
这个问题您可以暂时更新到【candy】的2.1.8-alpha，里面做了优化

**Comment by Joslyn-Chen** [comment]
@razerdp 额，是的，在decorView里添加了一个图片，后头我把图片移除后就正常了
