### ISSUE TITLE
有设备有崩溃情况

### ISSUE THREAD

**Issue by panyingdaoz** [razerdp/BasePopup#163]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本： 6.0
 - 库版本： implementation 'com.github.razerdp:BasePopup:2.1.7'
 - 问题描述/重现步骤： 鼠标右键或者遥控返回键就到导致应用奔溃
 - 问题代码/截图：
 - 报错信息：

03-22 15:22:18.847 2231-2231/com.kingbird.advertisting E/InputEventSender: Exception dispatching finished signal.
03-22 15:22:18.847 2231-2231/com.kingbird.advertisting E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
03-22 15:22:18.850 2231-2231/com.kingbird.advertisting E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.app.trust.ITrustManager.isDeviceLocked(int)' on a null object reference
                                                                               at android.os.Parcel.readException(Parcel.java:1605)
                                                                               at android.os.Parcel.readException(Parcel.java:1552)
                                                                               at android.content.IClipboard$Stub$Proxy.hasPrimaryClip(IClipboard.java:233)
                                                                               at android.content.ClipboardManager.hasPrimaryClip(ClipboardManager.java:156)
                                                                               at android.widget.TextView.canPaste(TextView.java:9441)
                                                                               at android.widget.TextView.onInitializeAccessibilityNodeInfoInternal(TextView.java:8971)
                                                                               at android.view.View.onInitializeAccessibilityNodeInfo(View.java:6078)
                                                                               at android.view.View.createAccessibilityNodeInfoInternal(View.java:6037)
                                                                               at android.view.View.createAccessibilityNodeInfo(View.java:6022)
                                                                               at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:145)
                                                                               at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:119)
                                                                               at android.view.View.onInitializeAccessibilityEventInternal(View.java:5974)
                                                                               at android.widget.TextView.onInitializeAccessibilityEventInternal(TextView.java:8919)
                                                                               at android.view.View.onInitializeAccessibilityEvent(View.java:5962)
                                                                               at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:5827)
                                                                               at android.view.View.sendAccessibilityEventUnchecked(View.java:5812)
                                                                               at android.widget.TextView.sendAccessibilityEventTypeViewTextChanged(TextView.java:9145)
                                                                               at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:10185)
                                                                               at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1033)
                                                                               at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:559)
                                                                               at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:492)
                                                                               at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:491)
                                                                               at android.text.method.NumberKeyListener.onKeyDown(NumberKeyListener.java:121)
                                                                               at android.widget.TextView.doKeyDown(TextView.java:6122)
                                                                               at android.widget.TextView.onKeyDown(TextView.java:5911)
                                                                               at android.view.KeyEvent.dispatch(KeyEvent.java:3063)
                                                                               at android.view.View.dispatchKeyEvent(View.java:9234)
                                                                               at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                               at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                               at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                               at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                               at android.widget.PopupWindow$PopupDecorView.dispatchKeyEvent(PopupWindow.java:1959)
                                                                               at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                               at razerdp.basepopup.PopupDecorViewProxy.dispatchKeyEvent(PopupDecorViewProxy.java:504)
                                                                               at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4131)
                                                                               at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4093)
                                                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
                                                                               at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3699)
                                                                               at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3665)
                                                                               at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3791)
                                                                               at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3673)
                                                                               at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3848)
                                                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
                                                                               at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3699)
                                                                               at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3665)
                                                                               at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3673)
                                                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
                                                                               at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3699)
                                                                               at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3665)
                                                                               at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3824)
                                                                               at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3985)
                                                                           	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.ja
03-22 15:22:19.526 2231-2231/com.kingbird.advertisting E/MtaSDK.CaughtExp: MTA has caught the following uncaught exception:
03-22 15:22:19.526 2231-2231/com.kingbird.advertisting E/MtaSDK.CaughtExp: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.app.trust.ITrustManager.isDeviceLocked(int)' on a null object reference
                                                                               at android.os.Parcel.readException(Parcel.java:1605)
                                                                               at android.os.Parcel.readException(Parcel.java:1552)
                                                                               at android.content.IClipboard$Stub$Proxy.hasPrimaryClip(IClipboard.java:233)
                                                                               at android.content.ClipboardManager.hasPrimaryClip(ClipboardManager.java:156)
                                                                               at android.widget.TextView.canPaste(TextView.java:9441)
                                                                               at android.widget.TextView.onInitializeAccessibilityNodeInfoInternal(TextView.java:8971)
                                                                               at android.view.View.onInitializeAccessibilityNodeInfo(View.java:6078)
                                                                               at android.view.View.createAccessibilityNodeInfoInternal(View.java:6037)
                                                                               at android.view.View.createAccessibilityNodeInfo(View.java:6022)
                                                                               at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:145)
                                                                               at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:119)
                                                                               at android.view.View.onInitializeAccessibilityEventInternal(View.java:5974)
                                                                               at android.widget.TextView.onInitializeAccessibilityEventInternal(TextView.java:8919)
                                                                               at android.view.View.onInitializeAccessibilityEvent(View.java:5962)
                                                                               at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:5827)
                                                                               at android.view.View.sendAccessibilityEventUnchecked(View.java:5812)
                                                                               at android.widget.TextView.sendAccessibilityEventTypeViewTextChanged(TextView.java:9145)
                                                                               at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:10185)
                                                                               at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1033)
                                                                               at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:559)
                                                                               at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:492)
                                                                               at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:491)
                                                                               at android.text.method.NumberKeyListener.onKeyDown(NumberKeyListener.java:121)
                                                                               at android.widget.TextView.doKeyDown(TextView.java:6122)
                                                                               at android.widget.TextView.onKeyDown(TextView.java:5911)
                                                                               at android.view.KeyEvent.dispatch(KeyEvent.java:3063)
                                                                               at android.view.View.dispatchKeyEvent(View.java:9234)
                                                                               at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                               at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                               at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                               at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                               at android.widget.PopupWindow$PopupDecorView.dispatchKeyEvent(PopupWindow.java:1959)
                                                                               at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                               at razerdp.basepopup.PopupDecorViewProxy.dispatchKeyEvent(PopupDecorViewProxy.java:504)
                                                                               at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4131)
                                                                               at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4093)
                                                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
                                                                               at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3699)
                                                                               at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3665)
                                                                               at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3791)
                                                                               at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3673)
                                                                               at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3848)
                                                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
                                                                               at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3699)
                                                                               at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3665)
                                                                               at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3673)
                                                                               at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
                                                                               at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3699)
                                                                               at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3665)
                                                                               at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3824)
                                                                               at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3985)
                                                                           	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.j
03-22 15:22:19.527 2231-2231/com.kingbird.advertisting E/MtaSDK.CaughtExp: App uncaught exception end.
                                                                           
                                                                           --------- beginning of crash
03-22 15:22:19.528 2231-2231/com.kingbird.advertisting E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.kingbird.advertisting, PID: 2231
                                                                         java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.app.trust.ITrustManager.isDeviceLocked(int)' on a null object reference
                                                                             at android.os.Parcel.readException(Parcel.java:1605)
                                                                             at android.os.Parcel.readException(Parcel.java:1552)
                                                                             at android.content.IClipboard$Stub$Proxy.hasPrimaryClip(IClipboard.java:233)
                                                                             at android.content.ClipboardManager.hasPrimaryClip(ClipboardManager.java:156)
                                                                             at android.widget.TextView.canPaste(TextView.java:9441)
                                                                             at android.widget.TextView.onInitializeAccessibilityNodeInfoInternal(TextView.java:8971)
                                                                             at android.view.View.onInitializeAccessibilityNodeInfo(View.java:6078)
                                                                             at android.view.View.createAccessibilityNodeInfoInternal(View.java:6037)
                                                                             at android.view.View.createAccessibilityNodeInfo(View.java:6022)
                                                                             at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:145)
                                                                             at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:119)
                                                                             at android.view.View.onInitializeAccessibilityEventInternal(View.java:5974)
                                                                             at android.widget.TextView.onInitializeAccessibilityEventInternal(TextView.java:8919)
                                                                             at android.view.View.onInitializeAccessibilityEvent(View.java:5962)
                                                                             at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:5827)
                                                                             at android.view.View.sendAccessibilityEventUnchecked(View.java:5812)
                                                                             at android.widget.TextView.sendAccessibilityEventTypeViewTextChanged(TextView.java:9145)
                                                                             at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:10185)
                                                                             at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1033)
                                                                             at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:559)
                                                                             at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:492)
                                                                             at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:491)
                                                                             at android.text.method.NumberKeyListener.onKeyDown(NumberKeyListener.java:121)
                                                                             at android.widget.TextView.doKeyDown(TextView.java:6122)
                                                                             at android.widget.TextView.onKeyDown(TextView.java:5911)
                                                                             at android.view.KeyEvent.dispatch(KeyEvent.java:3063)
                                                                             at android.view.View.dispatchKeyEvent(View.java:9234)
                                                                             at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                             at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                             at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                             at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                             at android.widget.PopupWindow$PopupDecorView.dispatchKeyEvent(PopupWindow.java:1959)
                                                                             at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1640)
                                                                             at razerdp.basepopup.PopupDecorViewProxy.dispatchKeyEvent(PopupDecorViewProxy.java:504)
                                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4131)
                                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4093)
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3699)
                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3665)
                                                                             at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3791)
                                                                             at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3673)
                                                                             at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3848)
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3699)
                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3665)
                                                                             at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3673)
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3646)
                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3699)
                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3665)
                                                                             at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3824)
                                                                             at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3985)
                                                                         	at android.view.inp

---

**Comment by razerdp** [comment]
tv的room可能改了底层导致这个原因，暂时无法重现且无法定位，该问题延迟解决。

**Comment by kevinwork** [comment]
我也出现这个问题，双指点击，再放开一个个放开，就会出现这个问题，我感觉是库的removeview逻辑问题？？
