### ISSUE TITLE
友盟统计的闪退日志

### ISSUE THREAD

**Issue by itkrly** [razerdp/BasePopup#174]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：android 5.1 
 - 库版本：2.0.8.1
 - 问题描述/重现步骤：部分机型有这个问题
 - 问题代码/截图：如下
![Uploading image.png…]()
![Uploading image.png…]()

 - 报错信息：
java.lang.IllegalArgumentException: View=razerdp.basepopup.PopupDecorViewProxy{3802c8c6 V.E..... ......I. 0,0-0,0} not attached to window manager
    at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:417)
    at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:316)
    at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:91)
    at razerdp.basepopup.WindowManagerWrapper.updateViewLayout(WindowManagerWrapper.java:126)
    at android.widget.PopupWindow.update(PopupWindow.java:1623)
    at android.widget.PopupWindow$1.onScrollChanged(PopupWindow.java:165)
    at android.view.ViewTreeObserver.dispatchOnScrollChanged(ViewTreeObserver.java:1016)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:2937)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2864)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2448)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1351)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6820)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:804)
    at android.view.Choreographer.doCallbacks(Choreographer.java:607)
    at android.view.Choreographer.doFrame(Choreographer.java:576)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:790)
    at android.os.Handler.handleCallback(Handler.java:815)
    at android.os.Handler.dispatchMessage(Handler.java:104)
    at android.os.Looper.loop(Looper.java:224)
    at android.app.ActivityThread.main(ActivityThread.java:5958)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)
---

**Comment by razerdp** [comment]
升级到最新版本。

**Comment by itkrly** [comment]
![image](https://user-images.githubusercontent.com/15819777/55861393-e10efd00-5ba8-11e9-9d62-880e5a359a52.png)

**Comment by razerdp** [comment]
升级到最新版本。，另外，，4.2.2实在太旧了，很多时候我都没有去测试到这个版本

**Comment by itkrly** [comment]
![image](https://user-images.githubusercontent.com/15819777/56077124-fa16e880-5e0a-11e9-85cd-98dc591a815f.png)

**Comment by itkrly** [comment]
![image](https://user-images.githubusercontent.com/15819777/56077138-2894c380-5e0b-11e9-92cb-743f33945d39.png)

**Comment by razerdp** [comment]
。。。最新版已经是2.1.9了- -2.0.8.1估计是10多个版本之前的事情
