### ISSUE TITLE
双指操作崩溃异常，同时双手分别按住两个选项，然后放开其中一个错误马上出现。

### ISSUE THREAD

**Issue by kevinwork** [razerdp/BasePopup#175]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：android 4.4.2
 - 库版本：2.1.9
 - 问题描述/重现步骤：

点击列表选项：单独点击不会出问题，同时双手分别按住两个选项，然后放开其中一个错误马上出现。
感觉应该是库的removeview逻辑问题

 - 问题代码/截图：

1.------------------------
public void onClick(String language) {
        VLog.d("on click:"+language);
        mLanguageSelectPopup.dismissWithOutAnimate();

2----------------------------------------------------------------------

package com.singapore.express.view;

import android.content.Context;
import android.view.Gravity;
import android.view.View;
import android.view.animation.Animation;
import android.view.animation.TranslateAnimation;
import android.widget.TextView;

import com.singapore.express.R;
import com.singapore.express.tool.VLog;

import javax.security.auth.callback.Callback;

import butterknife.Bind;
import butterknife.ButterKnife;
import butterknife.OnClick;
import razerdp.basepopup.BasePopupWindow;

/**
 * 类描述：
 * 创建人：kevin
 */
public class SelectPopup extends BasePopupWindow implements View.OnClickListener{

    private View mView;

    private ClickCallback mCallback;

    public SelectPopup(Context context, ClickCallback callback) {
        super(context);
        setPopupFadeEnable(true);
        ButterKnife.bind(mView);
        bindEvent();
        mCallback = callback;
    }

    // 必须实现，这里返回您的contentView
    // 为了让库更加准确的做出适配，强烈建议使用createPopupById()进行inflate
    @Override
    public View onCreateContentView() {
        mView = createPopupById(R.layout.layout_list_popup);
        return mView;
    }

    // 以下为可选代码（非必须实现）
    // 返回作用于PopupWindow的show和dismiss动画，本库提供了默认的几款动画，这里可以自由实现
/*    @Override
    protected Animation onCreateShowAnimation() {
        return getDefaultScaleAnimation(true);
    }

    @Override
    protected Animation onCreateDismissAnimation() {
        return getDefaultScaleAnimation(false);
    }*/

    private void bindEvent() {
        findViewById(R.id.tv_chinese).setOnClickListener(this);
        findViewById(R.id.tv_english).setOnClickListener(this);
        findViewById(R.id.tv_malay).setOnClickListener(this);
    }

    @Override
    public void onClick(View view) {
        switch (view.getId()) {
            case R.id.tv_chinese:
                mCallback.onClick("CHINESE");
                //VLog.d("CHINESE");
                break;
            case R.id.tv_english:
                mCallback.onClick("ENGLISH");
                //VLog.d("ENGLISH");
                break;
            case R.id.tv_malay:
                mCallback.onClick("MALAY");
                //VLog.d("MALAY");
                break;
            default:
                break;
        }
    }

    /**
     * 点击回调
     */
    public interface ClickCallback {
        void onClick(String language);
        void dismiss();
    }

    @Override
    public void showPopupWindow(View anchorView) {
        //initAnimate();
        super.showPopupWindow(anchorView);
    }

    @Override
    public boolean onOutSideTouch() {
        if (mCallback != null) {
            mCallback.dismiss();
        }
        return super.onOutSideTouch();
    }

    private void initAnimate() {

        int gravity = getPopupGravity();

        float in_fromX = 0;
        float in_toX = 0;
        float in_fromY = 0;
        float in_toY = 0;

        float exit_fromX = 0;
        float exit_toX = 0;
        float exit_fromY = 0;
        float exit_toY = 0;

        switch (gravity & Gravity.HORIZONTAL_GRAVITY_MASK) {
            case Gravity.LEFT:
            case Gravity.START:
                in_fromX = 1f;
                exit_toX = 1f;
                break;
            case Gravity.RIGHT:
            case Gravity.END:
                in_fromX = -1f;
                exit_toX = -1f;
                break;
            case Gravity.CENTER_HORIZONTAL:
                break;
            default:
                break;
        }
        switch (gravity & Gravity.VERTICAL_GRAVITY_MASK) {
            case Gravity.TOP:
                in_fromY = 1f;
                exit_toY = 1f;
                break;
            case Gravity.BOTTOM:
                in_fromY = -1f;
                exit_toY = -1f;
                break;
            case Gravity.CENTER_VERTICAL:
                break;
            default:
                break;
        }
        setShowAnimation(createTranslateAnimate(in_fromX, in_toX, in_fromY, in_toY));
        setDismissAnimation(createTranslateAnimate(exit_fromX, exit_toX, exit_fromY, exit_toY));
    }

    public Animation createTranslateAnimate(float fromX, float toX, float fromY, float toY) {
        Animation result = new TranslateAnimation(Animation.RELATIVE_TO_PARENT,
                fromX,
                Animation.RELATIVE_TO_PARENT,
                toX,
                Animation.RELATIVE_TO_PARENT,
                fromY,
                Animation.RELATIVE_TO_PARENT,
                toY);
        result.setDuration(200);
        return result;
    }

}

 - 报错信息：

### 04-19 10:07:20.939 6467-6467/com.singapore.express D/CrashHandler:uncaughtException(43): app uncaughtException
04-19 10:07:20.949 6467-6467/com.singapore.express D/CrashHandler:uncaughtException(57): java.lang.NullPointerException
        at android.view.ViewGroup.resetCancelNextUpFlag(ViewGroup.java:2011)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1957)
        at android.view.View.dispatchPointerEvent(View.java:7886)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3954)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3833)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3449)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3418)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3525)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3426)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3582)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3449)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3418)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3426)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5602)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5582)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5553)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5682)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:138)
        at android.os.Looper.loop(Looper.java:123)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
04-19 10:07:21.149 2761-2761/? D/VLog: WatcherService$1(108): android.intent.action.rousecourse.applystate
04-19 10:07:21.199 2761-2761/? D/VLog: WatcherService$1(108): android.intent.action.rousecourse.controlstate
04-19 10:07:21.929 6467-6944/com.singapore.express D/Group$CountDownTimerThread:run(271): mCountDownTime:59
---

**Comment by razerdp** [comment]
本库不会针对子控件进行任何的remove等操作。你可以装到更高版本的系统看看，因为我记得4.x好像曾经在measure的时候也出现过npe错误。属于系同级别的问题。

**Comment by kevinwork** [comment]
好的，我试试
