### ISSUE TITLE
在布局中使用recylerview+flexlayoutmanager报空指针

### ISSUE THREAD

**Issue by HelloMMMMM** [razerdp/BasePopup#196]
- 系统版本：
5.0及以上
 - 库版本：
2.2.0
 - 问题描述/重现步骤：
在布局中使用recylerview+flexlayoutmanager报空指针,recyclerview高度设置为wrap_content，固定高度正常
 - 问题代码/截图：
![image](https://user-images.githubusercontent.com/28476210/58627999-229b6900-830b-11e9-8677-153f6f4da23f.png)
![image](https://user-images.githubusercontent.com/28476210/58628029-36df6600-830b-11e9-99c3-96c1c182d1e8.png)

 - 报错信息：
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getWidth()' on a null object reference
        at com.google.android.flexbox.FlexboxLayoutManager.canScrollHorizontally(FlexboxLayoutManager.java:1898)
        at com.google.android.flexbox.FlexboxLayoutManager.getChildWidthMeasureSpec(FlexboxLayoutManager.java:485)
        at com.google.android.flexbox.FlexboxHelper.calculateFlexLines(FlexboxHelper.java:459)
        at com.google.android.flexbox.FlexboxHelper.calculateHorizontalFlexLines(FlexboxHelper.java:244)
        at com.google.android.flexbox.FlexboxLayoutManager.updateFlexLines(FlexboxLayoutManager.java:953)
        at com.google.android.flexbox.FlexboxLayoutManager.onLayoutChildren(FlexboxLayoutManager.java:729)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3336)
        at android.view.View.measure(View.java:17547)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5556)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
        at android.view.View.measure(View.java:17547)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5556)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
        at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1083)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:615)
        at android.view.View.measure(View.java:17547)
        at razerdp.basepopup.BasePopupWindow.preMeasurePopupView(BasePopupWindow.java:514)
        at razerdp.basepopup.BasePopupWindow.initView(BasePopupWindow.java:446)
        at razerdp.basepopup.BasePopupWindow.<init>(BasePopupWindow.java:397)
        at razerdp.basepopup.BasePopupWindow.<init>(BasePopupWindow.java:379)
        at razerdp.basepopup.BasePopupWindow.<init>(BasePopupWindow.java:369)
        at com.btten.teachermobile.dialog.study.StudyFilterPopWindow.<init>(StudyFilterPopWindow.java:26)
        at com.btten.teachermobile.study.StudyFragment.showFilterDialog(StudyFragment.java:94)
        at com.btten.teachermobile.study.StudyFragment.onClick(StudyFragment.java:82)
        at android.view.View.performClick(View.java:4780)
        at android.view.View$PerformClick.run(View.java:19866)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
---

**Comment by razerdp** [comment]
感觉跟basepopup关系不大
