### ISSUE TITLE
createPopupById(int layoutId) returns null 

### ISSUE THREAD

**Issue by elmliu** [razerdp/BasePopup#217]
- 系统版本：6.0.1
 - 库版本：2.2.1
 - 问题描述/重现步骤：
编译程序，报错如下：
`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.view.View.getContext()' on a null object reference
        at razerdp.basepopup.BasePopupWindowProxy.<init>(BasePopupWindowProxy.java:67)
        at razerdp.basepopup.PopupWindowProxy.<init>(PopupWindowProxy.java:17)
        at razerdp.basepopup.BasePopupWindow.initView(BasePopupWindow.java:436)
        at razerdp.basepopup.BasePopupWindow.<init>(BasePopupWindow.java:397)
        at razerdp.basepopup.BasePopupWindow.<init>(BasePopupWindow.java:379)
        at razerdp.basepopup.BasePopupWindow.<init>(BasePopupWindow.java:369)
        at com.example.elmliu.uniport.popup.FloatingPopup.<init>(FloatingPopup.java:48)
        at com.example.elmliu.uniport.activity.BaseActivity.initFloatingPopup(BaseActivity.java:169)
        at com.example.elmliu.uniport.activity.BaseActivity.setContentViewAndSetUpToolBar(BaseActivity.java:159)
        at com.example.elmliu.uniport.activity.visual.CircleMsg.onCreateCircleMsg(CircleMsg.java:47)
        at com.example.elmliu.uniport.activity.visual.CircleThree.onCreate(CircleThree.java:47)
        at android.app.Activity.performCreate(Activity.java:6361)`
最后可以定位到这里
```
public BasePopupWindowProxy(View contentView, int width, int height, BasePopupHelper helper) {
        super(contentView, width, height);
        this.mHelper = helper;
        init(contentView.getContext());
    }
```
而contentView是createPopupById()返回的结果
```
mContentView = onCreateContentView();
```
我的源码如下
```
@Override
    public View onCreateContentView() {
        return createPopupById(R.layout.popup_floating);
    }
```
刚升级到2.2.1，之前的2.1.9是没有这个问题的。
---

**Comment by razerdp** [comment]
日志只有这些吗，应该还有定位到BasePopupHelper.inflate()方法里的。

**Comment by elmliu** [comment]
@razerdp 又看了一遍，BasePopupHelper.inflate()还真没抛出错误

**Comment by razerdp** [comment]
可以去debug一下BasePopupHelper.inflate()方法里，因为contentView是这里inflate的~现在看起来信息不足，无法判断

**Comment by yasaman93** [comment]
Unfortunately, I have this issue too. I saw it in my application's firebase log, and I can't understand what the reason is, because you put a try/catch block in BasePopupHelper.inflate() method and the exception won't come to my firebase log.

**Comment by razerdp** [comment]
@yasaman93 ya,I have noticed this problem and started to deal with it, it will be fixed in the next version

**Comment by razerdp** [comment]
@elmliu 在最近几个issue里似乎也出现过类似问题，已经有点头绪了，在下一个版本里修复
