### ISSUE TITLE
void razerdp.basepopup.HackWindowManager.bindPopupHelper(razerdp.basepopup.BasePopupHelper)' on a null object reference

### ISSUE THREAD

**Issue by zhuzhengwei** [razerdp/BasePopup#229]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：Android10 api 29
 - 库版本：2.0.4  2.0.5-alpha
 - 问题描述/重现步骤：
 - 问题代码/截图：
QuickPopupBuilder.with(context)
                        .contentView(R.layout.jsl_image_select_layout)
                        .config(new QuickPopupConfig().withClick(R.id.camera_tv, new View.OnClickListener() {
                            @Override
                            public void onClick(View v) {

                            }
                        })).show();
另外 “.gravity”也没了？？

 - 报错信息：
at razerdp.basepopup.BasePopupWindowProxy.bindPopupHelper(BasePopupWindowProxy.java:82)
        at razerdp.basepopup.BasePopupWindow.initView(BasePopupWindow.java:377)
        at razerdp.basepopup.BasePopupWindow.<init>(BasePopupWindow.java:356)
        at razerdp.basepopup.BasePopupWindow.<init>(BasePopupWindow.java:350)
        at razerdp.basepopup.BasePopupWindow.<init>(BasePopupWindow.java:346)
---

**Comment by razerdp** [comment]
2.0.4已经是远古版本了。。。。。升级到最新吧

**Comment by razerdp** [comment]
手误点了close。。。。

**Comment by zhuzhengwei** [comment]
release版本信息显示的。。。

**Comment by razerdp** [comment]
你应该看readme.....  

release已经是很久很久以前打的，现在都不打release了

**Comment by razerdp** [comment]
我补了一下release的打包，，，发现挺多人不看readme的。。。
