### ISSUE TITLE
程序崩溃问题：在弹窗中滑动seekbar过程时再点击外部区域弹窗消失后程序崩溃

### ISSUE THREAD

**Issue by hapzhu** [razerdp/BasePopup#239]
- 系统版本：Android 5.1
 - 库版本：2.2.1
 - 问题描述/重现步骤：在弹窗里滑动seekbar时又在外部区域同时点击，弹窗消失后过一会，程序会崩溃
 - 问题代码/截图：
```
 public ControlPopupWindow(Context context) {
        super(context);
        unbinder = ButterKnife.bind(this,getContentView());
        initData();
        initView();
    }
   @Override
    public void onDismiss() {
        super.onDismiss();
        unbinder.unbind();
//        BarUtils.setStatusBarVisibility(getContext(),false);
    }
```
 - 报错信息：
```
E/InputEventReceiver: Exception dispatching input event.
E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mPrivateFlags' on a null object reference
        at android.view.ViewGroup.resetCancelNextUpFlag(ViewGroup.java:2187)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2104)
        at android.view.View.dispatchPointerEvent(View.java:8710)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4403)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4250)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3805)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3858)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3824)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3941)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3832)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3998)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3805)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3858)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3824)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3832)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3805)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6120)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6094)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6065)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6210)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:143)
        at android.os.Looper.loop(Looper.java:122)
        at android.app.ActivityThread.main(ActivityThread.java:5280)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
```

**Comment by razerdp** [comment]
崩溃信息没有一行跟basepopup相关。。。

**Comment by hapzhu** [comment]
我也觉得很奇怪，看不到是跟程序哪里的代码相关，但确实是与basePopup有关系。我换成原生的popupwindow就没事。
```
//        ControlPopupWindow controlPopupWindow = new ControlPopupWindow(this.getApplicationContext());
//        controlPopupWindow.setOutSideTouchable(false);
//        controlPopupWindow.showPopupWindow(ivTitleExpand);
        PopupWindow popupWindow = new PopupWindow(LayoutInflater.from(this).inflate(R.layout.popup_window_mediacontrol,null), ViewGroup.LayoutParams.WRAP_CONTENT,ViewGroup.LayoutParams.WRAP_CONTENT);
        popupWindow.setBackgroundDrawable(new ColorDrawable());
        popupWindow.setOutsideTouchable(true);
        popupWindow.showAsDropDown(ivTitleExpand);
```
我确定是用了basepopup这个库的
```
import razerdp.basepopup.BasePopupWindow;
public class ControlPopupWindow extends BasePopupWindow {}
```
我发现原生的popupwindow弹出来在滑动seekbar是不能点击外部非内容区域消失的，但basepopup在滑动时是可以点击外部区域消失，大佬你可以试下。

**Comment by razerdp** [comment]
点击外部是否消失是允许你控制的，setOutSideDismiss()

**Comment by razerdp** [comment]
https://github.com/razerdp/BasePopup/wiki/API#setoutsidedismissboolean-outsidedismiss

**Comment by hapzhu** [comment]
我在自己手机上(8.0系统)测试没有崩溃，但有一点是basepopup所特有的现象，就是当按住seekbar的滑动按钮时，再同时触碰外部区域整个弹窗会消失，即是两点同时触碰会让弹窗dismiss,可原生的popupwindow在按住seekbar时是无法点击外部区域使其消失的。我以为 popupWindow.setOutsideTouchable(false)会有作用，实际上还是会隐藏，有什么办法可以让用户在触碰内容弹窗区域时，不可点击外部区域使其dismiss吗。这里不是指设置外部不可点击setOutSideDismiss()。

**Comment by razerdp** [comment]
出现这个问题的原因估计在这一行代码

https://github.com/razerdp/BasePopup/blob/master/lib/src/main/java/razerdp/basepopup/PopupDecorViewProxy.java#L81

在你点击外部的时候，我会去搜索你点击的部分是否透传进而回调给basepopup的`onOutSideTouch`

https://github.com/razerdp/BasePopup/blob/master/lib/src/main/java/razerdp/basepopup/BasePopupWindow.java#L1833

你可以重写该方法进行你自己的操作~

关于这个问题我留意一下，因为我自己的测试并不能覆盖所有的场景，某些场景下确实可能会造成一些bug

**Comment by razerdp** [comment]
请更新到最新版本试试

demo测试结果如下：

![ezgif-1-91730224f4f4](https://user-images.githubusercontent.com/11629986/76495998-0a986e80-6473-11ea-9b26-032292a5491a.gif)

**Comment by razerdp** [comment]
无后续反馈，close

**Comment by Shirwee** [comment]
最新版本，在MIUI13上我也遇到了这个崩溃，setOutsideTouchable(true)和setOutSideDismiss(true)，多次两根手指同时点外部，就会出现这个崩溃。

**Comment by razerdp** [comment]
> 最新版本，在MIUI13上我也遇到了这个崩溃，setOutsideTouchable(true)和setOutSideDismiss(true)，多次两根手指同时点内容和外部，就会出现这个崩溃。

有报错日志吗。这两个一起使用会有可能导致popup dismiss但还要分发事件给外部，进而导致NPE崩溃

**Comment by Shirwee** [comment]
![image](https://user-images.githubusercontent.com/19380366/184280246-e884cdcb-26b1-4578-bf1a-d65a66250d6a.png)

**Comment by Shirwee** [comment]
也是报这个空指针异常

**Comment by Shirwee** [comment]
看了两天了，没有找到解决办法。

**Comment by Shirwee** [comment]
我们的页面效果是仿照大众点评的那个评分。

**Comment by Shirwee** [comment]
其他机型没有问题，MIUI12也没有，升级到MIUI13就会出现。
