### ISSUE TITLE
华为mate 20 android10  出现异常 

### ISSUE THREAD

**Issue by hyl87** [razerdp/BasePopup#257]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本： android10
 - 库版本：2.2.1
 - 问题描述/重现步骤：
 - 问题代码/截图：
 - 报错信息：
java.lang.NoSuchFieldException: No field mOnScrollChangedListener in class Landroid/widget/PopupWindow; (declaration of 'android.widget.PopupWindow' appears in /system/framework/framework.jar!classes
    at java.lang.Class.getDeclaredField(Native Method)
    at razerdp.basepopup.PopupReflectionHelper.preInject(PopupReflectionHelper.java:62)
    at razerdp.basepopup.BasePopupWindowProxy.troToProxyWindowManagerMethodOverP(BasePopupWindowProxy.java:185)
    at razerdp.basepopup.BasePopupWindowProxy.troToProxyWindowManagerMethodBeforeP(BasePopupWindowProxy.java:207)
    at razerdp.basepopup.BasePopupWindowProxy.tryToProxyWindowManagerMethod(BasePopupWindowProxy.java:176)
    at razerdp.basepopup.BasePopupWindowProxy.init(BasePopupWindowProxy.java:87)
    at razerdp.basepopup.BasePopupWindowProxy.<init>(BasePopupWindowProxy.java:67)
    at razerdp.basepopup.PopupWindowProxy.<init>(PopupWindowProxy.java:17)
    at razerdp.basepopup.BasePopupWindow.initView(BasePopupWindow.java:436)
    at razerdp.basepopup.BasePopupWindow.<init>(BasePopupWindow.java:397)
    at razerdp.basepopup.BasePopupWindow.<init>(BasePopupWindow.java:379)
    at razerdp.basepopup.BasePopupWindow.<init>(BasePopupWindow.java:369)
    at com.tmmtmm.im.state.PageLoadingDialog.<init>(PageLoadingDialog.kt:10)
---

**Comment by razerdp** [comment]
Android 10所有反射相关问题已知
@see 
#247 247

**Comment by razerdp** [comment]
等我寻找下一套方案后再适配
