### ISSUE TITLE
宿主窗口尚未准备好，等待准备就绪后弹出

### ISSUE THREAD

**Issue by xchengDroid** [razerdp/BasePopup#262]
### 提issue前请务必参考以下格式填写，否则该问题优先级将会降低

 - 系统版本：模拟器 6.0
 - 库版本：Candy 2.2.2.200203
 - 问题描述/重现步骤：无法弹出pop
 - 问题代码/截图：
 - 报错信息：
java.lang.IllegalStateException: 宿主窗口尚未准备好，等待准备就绪后弹出
        at razerdp.basepopup.BasePopupWindow.tryToShowPopup(BasePopupWindow.java:721)
        at razerdp.basepopup.BasePopupWindow.showPopupWindow(BasePopupWindow.java:610)
        at com.cosmap.onemap.MainMapActivity.onClick(MainMapActivity.java:190)
        at com.cosmap.onemap.MainMapActivity_ViewBinding$2.doClick(MainMapActivity_ViewBinding.java:61)
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:18)
        at android.view.View.performClick(View.java:5198)
        at android.view.View$PerformClick.run(View.java:21147)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
---

**Comment by razerdp** [comment]
问题已知，已经修复了，不过我还没打包，

**Comment by razerdp** [comment]
请更新到最新candy验证
