### ISSUE TITLE
BasePopupWindow.attachLifeCycle方法报空指针

### ISSUE THREAD

**Issue by YMLopez** [razerdp/BasePopup#269]
- 系统版本：三星Galaxy S8+ (samsung SM-G9550) Android9
 - 库版本：com.github.razerdp:BasePopup:2.2.1
 - 问题描述/重现步骤：
 - 问题代码/截图：
#（上传不了图- -）
> //显示隐私政策弹框
>                     PopupPrivacy popupPrivacy = new PopupPrivacy(MainActivity.this);
>                     popupPrivacy.setOutSideDismiss(false);
>                     popupPrivacy.showPopupWindow();

Activity onCreate()方法主线程里面延迟1秒后弹框报错
（根据异常收集平台上收集到的用户闪退日志，亲测并不能复现）
 - 报错信息：
```
2020-03-08 09:57:22.843,ip=120.231.76.154^country=中国^province=广东省^city=中山市^district=unknown,2020-03-08 09:57:24:354,161BC41101438_ANDROID-product,4.2.11,4,
-,-,22890f99412fdd738c3aeecd9eb8a32ee986778bbe4989c39e1aaf7f9f69270c,exception,foreground,-,ActivityApplicationStub,-,MonitorPoint_Crash,java.lang.NullPointerException:
	at razerdp.basepopup.BasePopupWindow.attachLifeCycle(Native Method)

	at razerdp.basepopup.BasePopupWindow.initView(Unknown Source:4)

	at razerdp.basepopup.BasePopupWindow.<init>(Unknown Source:15)

	at razerdp.basepopup.BasePopupWindow.<init>(Unknown Source:1)

	at razerdp.basepopup.BasePopupWindow.<init>(Unknown Source:1)

	at com.csii.launcher.widget.popup.PopupPrivacy.<init>(Unknown Source:0)

	at com.csii.launcher.activity.MainActivity$1.run(Unknown Source:4)

	at android.os.Handler.handleCallback(Handler.java:873)

	at android.os.Handler.dispatchMessage(Handler.java:99)

	at android.os.Looper.loop(Looper.java:214)

	at android.app.ActivityThread.main(ActivityThread.java:7050)

	at java.lang.reflect.Method.invoke(Native Method)

	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)

	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

,com.csii.launcher.activity.guide.GuideActivity_,mpaas_default,-,com.csii.launcher.fragment.IndexMineFragment_,com.csii.launcher.activity.guide.GuideActivity_,
fg,-,-,SM-G9550,9,WIFI,-,4.2.11,WWGoyffo0ykDAI3mKoxVqXQz,-,0,main,main,java,-,android.app.servertransaction.ClientTransaction@87a6cede,
romVersion=ppr1.180610.011.g9550zcu5dta1^hotpatchDesc=0^hotpatchBundleVersion=-^brand=samsung,27
```
---

**Comment by razerdp** [comment]
请更新的新版本

**Comment by YMLopez** [comment]
> 请更新的新版本

收到，谢谢
