### ISSUE TITLE
NullPointerException BasePopupWindow.superDismiss()

### ISSUE THREAD

**Issue by AndrLin** [razerdp/BasePopup#278]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void razerdp.basepopup.BasePopupWindow.superDismiss()' on a null object reference
	at razerdp.basepopup.BasePopupHelper$2.run(BasePopupHelper.java:828)
	at android.os.Handler.handleCallback(Handler.java:743)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5665)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
```
 - 系统版本：HUAWEI MLA-AL10(Android 6.0)、MI CC9 Pro(Android 9)
 - 库版本：'com.github.razerdp:BasePopup:2.2.2'

线上问题，没有更多日志，暂时不清楚什么场景导致的

**Comment by razerdp** [comment]
请更新到2.2.2.2，相关问题在readme的版本日志中有说。

**Comment by AndrLin** [comment]
您的回复太及时了，非常感谢！
