### ISSUE TITLE
android.view.WindowLeaked 

### ISSUE THREAD

**Issue by lapDog** [razerdp/BasePopup#44]
### 该问题是怎么引起的？
service回掉MainActivity的方法，方法执行弹出poupwindow方法，此时锚点VIew并未绘画完成。导致这个问题，使用WIKI中的三种方法均无效，使用延迟1秒后执行可行，但是想在此讨论是否有其他方法。

### 重现步骤
1.此方法调用弹出poupwindow
![image](https://user-images.githubusercontent.com/11813246/32934801-2009db84-cba8-11e7-82ea-b0b86f4a1375.png)
2.此方法为回调接口
![image](https://user-images.githubusercontent.com/11813246/32934829-367e7424-cba8-11e7-8723-1b74cd892f8e.png)
3.此处为拉起MainActivity.
![image](https://user-images.githubusercontent.com/11813246/32934843-471b4e88-cba8-11e7-83c8-1c83463b532e.png)

### 报错信息
E/WindowManager: android.view.WindowLeaked: Activity hjk.indi.cloudcontacts.activity.MainActivity has leaked window android.widget.PopupWindow$PopupViewContainer{2926b9e7 V.E..... ........ 0,0-929,453} that was originally added here
                     at android.view.ViewRootImpl.<init>(ViewRootImpl.java:373)
                     at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:271)
                     at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
                     at android.widget.PopupWindow.invokePopup(PopupWindow.java:1104)
                     at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1008)
                     at razerdp.basepopup.PopupWindowProxy.showAsDropDown(PopupWindowProxy.java:108)
                     at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:968)
                     at razerdp.basepopup.BasePopupWindow.tryToShowPopup(BasePopupWindow.java:480)
                     at razerdp.basepopup.BasePopupWindow.showPopupWindow(BasePopupWindow.java:468)
                     at hjk.indi.cloudcontacts.activity.DialPoupWindow.showPopupWindow(DialPoupWindow.java:110)

**Comment by lapDog** [comment]
![image](https://user-images.githubusercontent.com/11813246/32935454-36a9ee08-cbab-11e7-8b8a-8d5921b3481f.png)
解决了。。。监听锚点VIEW是否重绘完成，若完成更改flag.重绘完成情况下直接调用，未完成延迟调用。虽然有风险。先这样吧。。。

**Comment by razerdp** [comment]
@lapDog 

请问一下你现在用的版本是多少

在1.8.5.1之后，其实我在showPopup已经做了文章

您可以看看源码这里

[BasePopup](https://github.com/razerdp/BasePopup/blob/master/lib/src/main/java/razerdp/basepopup/BasePopupWindow.java)第512行

我针对BadTokenException进行过reTry，重试次数最高3次，每次延迟350ms。

不过还真没针对WindowLeak，因为WindowLeak一般是因为popup已经show，没有dismiss导致的

**Comment by lapDog** [comment]
最新版本。主要是我这个回调函数速度快于activity启动速度导致的吧。没有深入研究。。O(∩_∩)O

**Comment by razerdp** [comment]
好的，我试试按照你的代码复现，然后尝试修复
