### ISSUE TITLE
关于在popup中添加ComposeView错误

### ISSUE THREAD

**Issue by wosika** [razerdp/BasePopup#453]
系统版本（必须）/ System version (required)：Android10
库版本（必须）/ Library version (required)：3.2.0
问题代码/截图（可选）/ Problem code or screenshot (optional)：

我尝试在代码中这样写
``
class ComposePopup(context: Context, lifecycleOwner: LifecycleOwner) : BasePopupWindow(context) {

    init {
        bindLifecycleOwner(lifecycleOwner)
        setContentView(ComposeView(context).apply {
            setContent {
                Text(text = "123")
            }
        })
    }
}
``

调用时报错。未来是否会兼容compose?
` popup.showPopupWindow(x,y))
`

错误信息：
  java.lang.IllegalStateException: ViewTreeLifecycleOwner not found from razerdp.basepopup.PopupDecorViewProxy{2033453 V.E...... ......I. 0,0-0,0}
        at androidx.compose.ui.platform.WindowRecomposer_androidKt.createLifecycleAwareViewTreeRecomposer(WindowRecomposer.android.kt:244)
        at androidx.compose.ui.platform.WindowRecomposer_androidKt.access$createLifecycleAwareViewTreeRecomposer(WindowRecomposer.android.kt:1)
        at androidx.compose.ui.platform.WindowRecomposerFactory$Companion$LifecycleAware$1.createRecomposer(WindowRecomposer.android.kt:99)
        at androidx.compose.ui.platform.WindowRecomposerPolicy.createAndInstallWindowRecomposer$ui_release(WindowRecomposer.android.kt:155)
        at androidx.compose.ui.platform.WindowRecomposer_androidKt.getWindowRecomposer(WindowRecomposer.android.kt:230)
        at androidx.compose.ui.platform.AbstractComposeView.resolveParentCompositionContext(ComposeView.android.kt:244)
        at androidx.compose.ui.platform.AbstractComposeView.ensureCompositionCreated(ComposeView.android.kt:251)
        at androidx.compose.ui.platform.AbstractComposeView.onMeasure(ComposeView.android.kt:288)
        at android.view.View.measure(View.java:25477)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
        at android.view.View.measure(View.java:25477)
        at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1185)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:723)
        at android.view.View.measure(View.java:25477)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25477)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25477)
        at razerdp.basepopup.PopupDecorViewProxy.measureWrappedDecorView(PopupDecorViewProxy.java:361)
        at razerdp.basepopup.PopupDecorViewProxy.onMeasure(PopupDecorViewProxy.java:189)
        at android.view.View.measure(View.java:25477)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3265)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2016)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2315)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1880)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8570)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1069)
        at android.view.Choreographer.doCallbacks(Choreographer.java:874)
        at android.view.Choreographer.doFrame(Choreographer.java:808)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1054)
        at android.os.Handler.handleCallback(Handler.java:883)

**Comment by razerdp** [comment]
暂不考虑哦~

**Comment by fansangg** [comment]
我是这样处理的

                        ```
FrameLayout.apply{
  id = android.R.id.content
			ViewTreeLifecycleOwner.set(this, lifecycleOwner)
			setViewTreeSavedStateRegistryOwner(saveOwner)
			addView(composeView)
}
```

```
val lifecycleOwner = LocalLifecycleOwner.current
			val stateRegistryOwner = LocalSavedStateRegistryOwner.current
val stroageTips = remember {
				StroageTips(this,lifecycleOwner, stateRegistryOwner)
			}
```

这样就能显示composeview了

**Comment by fansangg** [comment]
这样操作可以在basepopup里使用composeview

popup 代码

```
init{
    val composeView = ComposeView(context).apply {
			setContent { }

   val frameLayout = FrameLayout(context).apply {
			id = android.R.id.content
			ViewTreeLifecycleOwner.set(this, lifecycleOwner)
			setViewTreeSavedStateRegistryOwner(saveOwner)
			layoutParams = FrameLayout.LayoutParams(
				ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT
			)
			addView(composeView)
		}
		contentView = frameLayout
}
```

在Composable中

```
val lifecycleOwner = LocalLifecycleOwner.current
val stateRegistryOwner = LocalSavedStateRegistryOwner.current
val popup = remember {
				BasePopup(this,lifecycleOwner, stateRegistryOwner)
			}
```

然后在你需要显示的地方显示就行了

**Comment by razerdp** [comment]
噢~裹多一层吗

**Comment by fansangg** [comment]
> 噢~裹多一层吗

主要是加上这个
        id = android.R.id.content
			ViewTreeLifecycleOwner.set(this, lifecycleOwner)
			setViewTreeSavedStateRegistryOwner(saveOwner)
