### ISSUE TITLE
BasePopup中使用ViewPager2+Fragment没问题，FragmentManager.beginTransaction()报错

### ISSUE THREAD

**Issue by ijero** [razerdp/BasePopup#465]
- 系统版本（必须）/ System version (required)：Android 10
 - 库版本（必须）/ Library version (required)：3.0.7
 - 问题代码/截图（可选）/ Problem code or screenshot (optional)：
```kotlin
class MarketIndexPopup(
    private val activity: AppCompatActivity,
    private val stkInfo: Jclprotocol.StkInfoNew
) : BottomPopup(activity, R.layout.popup_market_index) {

    // ... 
    override fun onViewCreated(contentView: View) {
        binding = PopupMarketIndexBinding.bind(contentView).apply {
            val fm = activity.supportFragmentManager
            radioGroup.setOnCheckedChangeListener { group, checkedId ->
                val index = group.indexOfChild(group.findViewById<RadioButton>(checkedId))
                val fragment = indexFragments(index)
                fm.beginTransaction()
                    .replace(R.id.frame_layout, fragment)
                    .commit()
             }
         }
     }
    // ...
}
```
 - 报错信息（可选）/ Error reporting information (optional)：
```kotlin
    java.lang.IllegalArgumentException: No view found for id 0x7f0a01bb (com.karen.goldstrategy:id/frame_layout) for fragment StockDataFragment{f2dad1b} (894dd5ef-3a2d-4cf3-951b-0b79585be2e8 id=0x7f0a01bb)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:513)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

---

> 问题描述/重现步骤
> Please write the description here.

为什么我在BasePopup中使用ViewPager2+Fragment 可以，但是用FragmentManager.beginTransaction()提交就报错找不到 ID

**Comment by ijero** [comment]
以上是出问题的代码，项目中使用ViewPager2+Fragment 完全没问题

**Comment by razerdp** [comment]
请查看手册，常见问题

**Comment by guodonghuang** [comment]
我也出現了這個問題，原因是fragmen的容器在popwindow中，而管理器activity.supportFragmentManager是依附activity，所以在activity的佈局裏找不到fragmen的容器，No view found for id，可是，如何破解呢，作者好像沒有説明白，不知道解決了嗎！靜待佳音！

**Comment by razerdp** [comment]
> 我也出現了這個問題，原因是fragmen的容器在popwindow中，而管理器activity.supportFragmentManager是依附activity，所以在activity的佈局裏找不到fragmen的容器，No view found for id，可是，如何破解呢，作者好像沒有説明白，不知道解決了嗎！靜待佳音！

是的，你找到了问题根源。简单的说就是popup中的frag想去act找存在于pop中的viewpager。（锅在于viewpager fragmentadapter）
当初想过一种方式，就是替换根布局对相应的接口进行hook，不过我没试过。
另一种就是wrap一下context，装饰一下对相关方法进行hook。

最终没去做的原因也很简单，这一系列的操作可能会引发更奇怪的bug，毕竟开发者可能不会发现自己传进来的view或者context被偷偷代理掉或者被包一层，最终导致想调用某些方法时出问题。
