### ISSUE TITLE
java.lang.NullPointerException 空指针异常

### ISSUE THREAD

**Issue by pichsy** [razerdp/BasePopup#508]
04-02 09:11:17.850  5053  5053 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
04-02 09:11:17.850  5053  5053 E AndroidRuntime: 	at razerdp.basepopup.PopupDecorViewProxy.onKeyboardChange(PopupDecorViewProxy.java:42)
04-02 09:11:17.850  5053  5053 E AndroidRuntime: 	at razerdp.basepopup.BasePopupHelper.onKeyboardChange(BasePopupHelper.java:5)
04-02 09:11:17.850  5053  5053 E AndroidRuntime: 	at razerdp.basepopup.BasePopupHelper$2.onKeyboardChange(BasePopupHelper.java:3)
04-02 09:11:17.850  5053  5053 E AndroidRuntime: 	at com.huawei.hms.hem.cd0.onGlobalLayout(KeyboardUtils.java:148)
04-02 09:11:17.850  5053  5053 E AndroidRuntime: 	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1071)
04-02 09:11:17.850  5053  5053 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4387)
04-02 09:11:17.850  5053  5053 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2959)
04-02 09:11:17.850  5053  5053 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10878)
04-02 09:11:17.850  5053  5053 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1562)
04-02 09:11:17.850  5053  5053 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:1227)
04-02 09:11:17.850  5053  5053 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:1109)
04-02 09:11:17.850  5053  5053 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1518)
04-02 09:11:17.850  5053  5053 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:966)
04-02 09:11:17.850  5053  5053 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
04-02 09:11:17.850  5053  5053 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
04-02 09:11:17.850  5053  5053 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:293)
04-02 09:11:17.850  5053  5053 E AndroidRuntime: 	at android.app.ActivityThread.loopProcess(ActivityThread.java:9832)
04-02 09:11:17.850  5053  5053 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:9821)
04-02 09:11:17.850  5053  5053 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-02 09:11:17.850  5053  5053 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)

> 问题描述/重现步骤请写在这里
> Please write the description here.
弹起弹窗-等待，过没多久，就会发生。华为鸿蒙3.1.0

**Comment by hewh7** [comment]
<img width="1491" height="487" alt="Image" src="https://github.com/user-attachments/assets/99ea1b87-ec4f-481f-92f4-d3fb8c6e8967" />
看样子是application为空导致的空指针, 你可以试试
