### ISSUE TITLE
java.lang.ClassCastException: android.view.ViewGroup$LayoutParams cannot be cast to android.view.WindowManager$LayoutParams

### ISSUE THREAD

**Issue by XZWQuickness** [razerdp/BasePopup#52]
### 该问题是怎么引起的？

  at android.widget.PopupWindow$1.onScrollChanged(PopupWindow.java:149)
                                                                               at android.view.ViewTreeObserver.dispatchOnScrollChanged(ViewTreeObserver.java:1016)
                                                                               at android.view.ViewRootImpl.draw(ViewRootImpl.java:2464)
                                                                               at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2396)
                                                                               at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2026)
                                                                               at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1104)
                                                                               at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5962)
                                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:794)
                                                                               at android.view.Choreographer.doCallbacks(Choreographer.java:607)
                                                                               at android.view.Choreographer.doFrame(Choreographer.java:577)
                                                                               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:780)
                                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:135)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5296)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)

### 报错信息/系统版本

```java

```

### 建议或优化点

**Comment by ParfoisMeng** [comment]
+1 

`java.lang.ClassCastException: android.view.ViewGroup$LayoutParams cannot be cast to android.view.WindowManager$LayoutParams
                                                                           at android.widget.PopupWindow.getDecorViewLayoutParams(PopupWindow.java:2282)
                                                                           at android.widget.PopupWindow.alignToAnchor(PopupWindow.java:2427)
                                                                           at android.widget.PopupWindow.lambda$-android_widget_PopupWindow_10383(PopupWindow.java:262)
                                                                           at android.widget.-$Lambda$ISuHLqeK-K4pmesAfzlFglc3xF4$1.$m$0(Unknown Source:17)
                                                                           at android.widget.-$Lambda$ISuHLqeK-K4pmesAfzlFglc3xF4$1.onLayoutChange(Unknown Source:0)
                                                                           at android.view.View.layout(View.java:19799)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:6144)
                                                                           at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2653)
                                                                           at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2356)
                                                                           at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1512)
                                                                           at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7218)
                                                                           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:981)
                                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:790)
                                                                           at android.view.Choreographer.doFrame(Choreographer.java:721)
                                                                           at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
                                                                           at android.os.Handler.handleCallback(Handler.java:808)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:101)
                                                                           at android.os.Looper.loop(Looper.java:166)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:7415)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)`

**Comment by ParfoisMeng** [comment]
> java.lang.ClassCastException: android.view.ViewGroup$LayoutParams cannot be cast to android.view.WindowManager$LayoutParams
                                                                           at android.widget.PopupWindow.getDecorViewLayoutParams(PopupWindow.java:2282)
                                                                           at android.widget.PopupWindow.alignToAnchor(PopupWindow.java:2427)
                                                                           at android.widget.PopupWindow.lambda$-android_widget_PopupWindow_10383(PopupWindow.java:262)
                                                                           at android.widget.-$Lambda$ISuHLqeK-K4pmesAfzlFglc3xF4$1.$m$0(Unknown Source:17)
                                                                           at android.widget.-$Lambda$ISuHLqeK-K4pmesAfzlFglc3xF4$1.onLayoutChange(Unknown Source:0)
                                                                           at android.view.View.layout(View.java:19799)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:6144)
                                                                           at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2653)
                                                                           at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2356)
                                                                           at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1512)
                                                                           at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7218)
                                                                           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:981)
                                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:790)
                                                                           at android.view.Choreographer.doFrame(Choreographer.java:721)
                                                                           at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
                                                                           at android.os.Handler.handleCallback(Handler.java:808)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:101)
                                                                           at android.os.Looper.loop(Looper.java:166)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:7415)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)


相同的错误吧

**Comment by razerdp** [comment]
@XZWQuickness 
@ParfoisMeng 

请问是什么版本，以及复现步骤

**Comment by XZWQuickness** [comment]
小米2a 5.1.1 多次点击显示showPopupWindow 销毁dismiss 就出现了

**Comment by XZWQuickness** [comment]
小米2a 版本5.1.1 多次显示showPopupWindow 销毁dismiss 就会出现

**Comment by razerdp** [comment]
好的，我尽快解决

**Comment by XZWQuickness** [comment]
在单独activity 、Fragment没有问题。在三层fragent嵌套最后一层fragent中会出现这个问题。

**Comment by razerdp** [comment]
其实是跟一个滑动有关大概，因为popup内部有监听scroll事件（用于将popup与anchorView对齐的）

而因为popup给add到windowmanager时用的是WindowManager.LayoutParams，而我这边因为hack掉windowmanager同时在addView时，给内部的decorView再加一层，导致了一个问题，就是两边的layoutParams可能不一致。

详情定位到：

popupwindow-> `alignToAnchor()`方法(源码点我)
[https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/widget/PopupWindow.java#2347]

外部scroll时回调到scrolllistener，其内部有获取layoutParams方法

```java
final WindowManager.LayoutParams p = getDecorViewLayoutParams();
```

这里因为decorView被我add到了hackpopupdecorView，因此被我转为了viewGroup的LayoutParams，这里报错可能是因为向下转型的问题，目前解决方案我来想想哈。。。


[hackwindowmanager](https://github.com/razerdp/BasePopup/blob/master/lib/src/main/java/razerdp/basepopup/HackWindowManager.java#L85)

**Comment by ParfoisMeng** [comment]
@razerdp 1.8.2没问题，1.9.2崩溃，中间版本未测试。

**Comment by razerdp** [comment]
嗯呐，1.9.1开始用windowmanager代理这个方法，当时自己测试也没遇到这个问题，现在遇到的话我在下个版本解决哈~

顺便问下- -崩溃频率高不高

**Comment by XZWQuickness** [comment]
有些机型崩溃蛮高的，比如小米2a

**Comment by liaolintao** [comment]
我也遇到这个问题了, 挺容易触发的.

## 信息
BasePopup:1.9.2;
手机魅蓝note5, android6.0,

## 重新步骤
1.showPopupWindow(view);
2. 点击空白, pop消失

反复几次就crash了.

**Comment by Mr-PolarBear** [comment]
我也遇到了哈   
当同个页面 有一个textview setSelected(true)(由于文字太长  文字横向滚动  跑马灯效果)  
这时候点击显示popupwindow 会报这个错误

还有个问题顺便反馈下 - -  

新版本  1.9.2 input类型的popupwindow 不会自动随输入法 而弹到上方 如果屏幕太小 输入法会遮住popupwindow

**Comment by ParfoisMeng** [comment]
@razerdp 我那样的使用方式操作流程，崩溃是必现的。他们的问题不清楚是否必现，但概率应该都很高

**Comment by razerdp** [comment]
@Mr-PolarBear 

那个输入法的问题是跟全屏有关的，因为popupHelper默认全屏（N以上可以把popup覆盖到状态栏）[BasePopupHelper#50](https://github.com/razerdp/BasePopup/blob/master/lib/src/main/java/razerdp/basepopup/BasePopupHelper.java#L50)、[HackWindowmanager#180](https://github.com/razerdp/BasePopup/blob/master/lib/src/main/java/razerdp/basepopup/HackWindowManager.java#L180)

所以布局无法顶上去，又因为这个跟activity全屏一样，当设置为全屏flag` LayoutParams.FLAG_LAYOUT_IN_SCREEN`时，输入法就已经是由window来控制了，所以布局无法resize，这个问题暂时无解

目前来说，可以禁用全屏来折中：
```java
popup.setPopupWindowFullScreen(false);
```

**Comment by liaolintao** [comment]
已解决, 谢谢!

## 验证步骤

1.在外侧滚动RecyclerView
2.在RecyclerView还未停下来的时候, `showPopupWindow(view)`

**Comment by razerdp** [comment]
3Q，如果还有什么问题欢迎提交issue哦

**Comment by yang0000meng** [comment]
我也遇到了哈  ,调试了一下午，唉。。

**Comment by razerdp** [comment]
@yang0000meng  你好，可以开个新的issue具体描述下吗。。。。。还有重现方案- 

recyclerview在demo中[DismissControlPopupFrag](https://github.com/razerdp/BasePopup/blob/master/app/src/main/java/razerdp/demo/fragment/DismissControlPopupFrag.java)也有哦。

**Comment by hezhipengzipp** [comment]
吓得我赶紧升级1.9.3
