### ISSUE TITLE
使用MenuPopup问题

### ISSUE THREAD

**Issue by hudan2714** [razerdp/BasePopup#53]
### 该问题是怎么引起的？

 java.lang.AbstractMethodError: abstract method not implemented
                                                                          at razerdp.basepopup.HackWindowManager.getGlobalSystemUiVisibility(HackWindowManager.java)
                                                                          at android.widget.PopupWindow.getVisibleDisplayRect(PopupWindow.java:1439)
                                                                          at android.widget.PopupWindow.findDropDownPosition(PopupWindow.java:1274)
                                                                          at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:946)
                                                                          at razerdp.basepopup.PopupWindowProxy.callSuperShowAsDropDown(PopupWindowProxy.java:48)
                                                                          at razerdp.basepopup.PopupCompatManager$ImplBefore24.showAsDropDown(PopupCompatManager.java:145)
                                                                          at razerdp.basepopup.PopupCompatManager.showAsDropDown(PopupCompatManager.java:23)
                                                                          at razerdp.basepopup.PopupWindowProxy.showAsDropDownProxy(PopupWindowProxy.java:35)
                                                                          at razerdp.basepopup.BasePopupWindow.tryToShowPopup(BasePopupWindow.java:469)
                                                                          at razerdp.basepopup.BasePopupWindow.showPopupWindow(BasePopupWindow.java:456)

### 报错信息/系统版本

```java

```

### 建议或优化点

**Comment by razerdp** [comment]
请问版本多少。。。

**Comment by hudan2714** [comment]
最新版本的。。最近刚集成进来

**Comment by razerdp** [comment]
请问你的系统版本是多少，根据logcat，似乎是api24之前，我用api18(android 4.3.1)测试并没有重现这个问题
