### ISSUE TITLE
Android P模拟器中崩溃了。

### ISSUE THREAD

**Issue by mppy1** [razerdp/BasePopup#73]
### 该问题是怎么引起的？
直接打开就空指针了。

### 报错信息/系统版本
 java.lang.NullPointerException: Attempt to invoke virtual method 'void razerdp.basepopup.HackWindowManager.bindPopupHelper(razerdp.basepopup.BasePopupHelper)' on a null object reference
        at razerdp.basepopup.BasePopupWindowProxy.bindPopupHelper(BasePopupWindowProxy.java:85)
        at razerdp.basepopup.BasePopupWindow.initView(BasePopupWindow.java:280)
        at razerdp.basepopup.BasePopupWindow.<init>(BasePopupWindow.java:264)
```java

```

### 建议或优化点

**Comment by razerdp** [comment]
@mppy1 p还没去适配，因为p限制了@hide的反射，所以有点麻烦。暂时p无法使用
