### ISSUE TITLE
android 系统9.0崩溃

### ISSUE THREAD

**Issue by Xiaa520** [razerdp/BasePopup#99]
java.lang.NullPointerException: Attempt to invoke virtual method 'void razerdp.basepopup.HackWindowManager.bindPopupHelper(razerdp.basepopup.BasePopupHelper)' on a null object reference
        at razerdp.basepopup.BasePopupWindowProxy.bindPopupHelper(BasePopupWindowProxy.java:82)
        at razerdp.basepopup.BasePopupWindow.initView(BasePopupWindow.java:377)
        at razerdp.basepopup.BasePopupWindow.<init>(BasePopupWindow.java:356)
        at razerdp.basepopup.BasePopupWindow.<init>(BasePopupWindow.java:350)
        at razerdp.basepopup.BasePopupWindow.<init>(BasePopupWindow.java:346)

**Comment by razerdp** [comment]
版本？

**Comment by manburenshenglu** [comment]
android 9.0华为手机崩溃，库版本：2.0.5-alpha。相同的错误日志： Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void razerdp.basepopup.HackWindowManager.bindPopupHelper(razerdp.basepopup.BasePopupHelper)' on a null object reference
